import Handlebars from './registerPartials';

export const source = `# Base FHIR module for FHIR 4.0.1
# This file is autogenerated by 'npm run generate-mongoid', do not modify. 
# If needs, updates should be made in model-info-parser
module FHIR
end

require 'mongoid'

{{#each names}}
require_relative 'fhir/{{this}}'
{{/each}}
`;

export interface TemplateContext {
  names: Array<string>;
}

export default Handlebars.compile<TemplateContext>(source);
