import Handlebars from "./registerPartials";

export const source = `# Base FHIR module for FHIR 4.0.1
# This file is autogenerated by running 'npm run generate-mongoid', do not modify
module FHIR
end

require 'mongoid'

{{#each names}}
require_relative 'fhir/{{this}}'
{{/each}}
`;

export interface TemplateContext {
  names: Array<string>;
}

export default Handlebars.compile<TemplateContext>(source);
